### ISSUE TITLE
Implement maven-based or ant-based build

### ISSUE THREAD

**Issue by sferencik** [mendhak/teamcity-graphite#13]
To make it possible to build the plugin on a CI server, implement a build based on maven or ant.

**Comment by sferencik** [comment]
@mendhak, if you agree, I'd try to implement a maven-based build. OK?

**Comment by mendhak** [comment]
If possible that would be great!

**Comment by sferencik** [comment]
6d53876e5aba50bdffb61a5f631ed41fbe3a1ec5
