### ISSUE TITLE
Allow sending non-timer metrics as gauges (rather than counters)

### ISSUE THREAD

**Issue by sferencik** [mendhak/teamcity-graphite#17]
When sending over UDP (StatsD), we're sending
* time-related data (durations) as timers
* the rest as counters

I believe the counters are the wrong concept here, and gauges are more appropriate. A counter goes to 0 every time the metric is not sent. Thus, if we have one-minute buckets, and our build finishes, completing 35 tests, the counter is set to 35 for that bucket. The next bucket, however, when no stats is sent, the counter clocks 0. The resultant graph crawls at 0 and then spikes to 35 here and there. The problems with this are threefold:
1. it's visually messy (one can work around this by displaying `removeBelowValue(my.metric, 1)`, and thus turn the 0s into NULLs, then use connected line)
2. the aggregation doesn't work well; when smaller buckets need to be aggregated into bigger ones, and averaging is used, Graphite calculates the average of sparse 35s with dense 0s, producing a nonsensically low number
3. it's simply the wrong abstraction; looking at the standard build statistics, not one of them should behave like a counter

In contrast, gauges stay at the last recorded value. Thus, the graph will remain flat at 35 until a test is added, at which point it will step up to 36.

I'm tempted not to add this as an option (use counters or use gauges) but to actually change it to gauges without asking the users. That's because, especially given point 2 above, I think no-one can sensibly be using the counters; the averaging just doesn't work. Also, making this configurable would further clutter the config dialog (and it only applies if UDP is used).

**Comment by sferencik** [comment]
We've been using TeamCity-Graphite for over a year, but we never cared for the non-timer metrics. Now that I looked at them, they suffer exactly what I described: they are useless past the first aggregation. I'll just change counters for gauges.

**Comment by sferencik** [comment]
As I've just read [here](https://github.com/etsy/statsd/blob/master/docs/metric_types.md), maybe the zeroes can be replaced by NULLs in counters (`config.deleteCounters`). However, it's still true that none of the standard TC metrics is a counter; logically they are all gauges.

**Comment by mendhak** [comment]
I wonder if gauges are relatively new, this is the first I've heard of
them, I couldn't find any gauges areas in my graphite dashboard either.

**Comment by sferencik** [comment]
I would say gauges have been around as long as the timers have. (That's in StatsD, not directly in Graphite.) Do you use the timers, or plain Graphite? There's some background on the history of StatsD [here](https://github.com/iamcal/Flickr-StatsD) and [here](https://github.com/b/statsd_spec) - good reads in their own right.

When you say you don't use gauges, does that mean you use some of the TeamCity metrics as counters?

**Comment by sferencik** [comment]
Subhendu recommends [this post](https://blog.pkhamre.com/understanding-statsd-and-graphite/) to understand StatsD. I agree it's quite instructive.

**Comment by sferencik** [comment]
OK, I've made the change now.

@mendhak , if you're OK with this, please release. In the release notes, please say something like this:

> If you use the *Use StatsD via UDP* option, your counters will now change to gauges. This means slightly different handling on the Graphite side, and the metric keys will also change (`stats.foo.bar` becomes `stats.gauges.foo.bar`). On the other hand, the aggregation of your metrics will work correctly; see #17.

**Comment by mendhak** [comment]
OK that's done now thanks, also added updated graphite.zip

**Comment by sferencik** [comment]
Thank you. I've taken the bolder approach, which is backwards incompatible, because I can't imagine how the counters could be useful to anyone in this form. If, however, someone complains, I'm happy to fix this to allow both counters and gauges.

**Comment by mendhak** [comment]
Yes, we'll need to... gauge... their reaction :laughing:

**Comment by sferencik** [comment]
Haha. Count the complaints 😀

**Comment by bronumski** [comment]
@mendhak & @sferencik - Ha ha you guys crack me up... good timers good timers.

Well had to try something.

I am about to use this build feature so I can give you feedback if I don't get what I am expecting.
