### ISSUE TITLE
TeamCity Build Number

### ISSUE THREAD

**Issue by mrlov** [mendhak/teamcity-graphite#18]
Hi, folks!
Is there a reason why the Build Number parameter is not sent with all the other stats?
You could use the build number for example to build a link to the associated build on the TeamCity web frontend....
Regards

**Comment by sferencik** [comment]
I am not aware of any specific reason. Can you please elaborate on where you would "build a link"? Would that be a link from somewhere in Graphite? How?

**Comment by mrlov** [comment]
I am using Grafana with Graphite
Example from Grafana:  Table panel with clickable cell links using any row column value in link

>  To make a column with link cells you add a column style and check the Render value as link checkbox. That will make the link url & tooltip options appear.
> You can use the cell value or other cell values in the link url using $__cell or $__cell_n' where n refers to Nth column value in current row.

see: https://github.com/grafana/grafana/issues/3754#issuecomment-319193071

**Comment by sferencik** [comment]
I see. So you would store the build ID in Graphite, then synthesize the full URL in Graphana, and render it as URL. Is that what you want?

What I still don't understand is this:
* how would you "match" (1) the hyperlink to the build and (2) the metrics corresponding to the build?
* data in Graphite is always treated as numeric, and Graphite performs algebraic operations with it; thus if two builds, let's call them 1234 and 1236, finish at approximately the same time, Graphite will store them as a single data point (bucket) with value 1235. Especially older data tends to get mixed together into increasingly large buckets (for today's data, you may keep them in 1-minute buckets, but data from a month ago would be in day-long buckets etc.). Am I missing something?

**Comment by mrlov** [comment]
Yes, that is what I want.

I am no expert for time series databases and could not foreseen such implications. In my naiveté I thought I could assign any information to a point in time, similar to the metrics the Jenkins-InfluxDB-Plugin provides (see https://wiki.jenkins.io/display/JENKINS/InfluxDB+Plugin).

But as I understand now, it depends on the capabilities of the underlying time series database.

Thus consider this issue as invalid.

**Comment by sferencik** [comment]
Makes sense, thanks.

**Comment by mrlov** [comment]
Thanks!
