### ISSUE TITLE
Won't load on TeamCity 2017.1.2.

### ISSUE THREAD

**Issue by hunhejj** [mendhak/teamcity-graphite#19]
Tried to install this on TeamCity v2017.1.2. 
Placed the zip to the plugins folder and restarted TeamCity, however it did not show up. Looked at the server logs and it doesn't seem to even try to load anything from the .zip file.
Are there maybe compatibility issues with newer TeamCity or are we doing something wrong?

**Comment by mendhak** [comment]
There shouldn't be any problem.

What folder path did you put it in?

When you go back to the folder you placed the .zip in, do you find an unzipped companion?  TeamCity server will unzip any plugins that you place in the plugins folder.  If nothing has been unzipped then definitely something is up with the server. 

Check the admin page, plugins section - anything showing up there?

You can also try deleting the zip, re-downloading to be sure.  Try unzipping it yourself to make sure it's not corrupt

**Comment by hunhejj** [comment]
We did everything that was suggested and in the end it got installed. (Don't ask what solved the issue because we don't know:). Thank you for the help!
