### ISSUE TITLE
counters vs timers

### ISSUE THREAD

**Issue by sferencik** [mendhak/teamcity-graphite#2]
Hi mendhak,

StatsD (the UDP mode) distinguishes between counters and timers [https://github.com/etsy/statsd/]. It would be really neat if teamcity-graphite sent the time values (e.g. "buildcheckouttime" or the various "buildstageduration/*" metrics) as timers.

Would you be open to changing GraphiteClient to send "k:v|ms" instead of "k:v|c" for these? Or to do this optionally, subject to a setting in the Build Feature form? (By default, it would still send these as counters.)

If you have no objections, I can send a pull request.

Thanks,
Sam

**Comment by mendhak** [comment]
A pull request would be great!  An option in the Build Feature form would be the best so that it's somewhat backwards compatible.

**Comment by sferencik** [comment]
Thanks. I'll send a pull request later today. Until then, here's a screenshot of the Build Feature dialog, with my changes highlighted. Feel free to comment.

As you see, I felt the need to highlight that this is only relevant for StatsD, hence the added info in the "Use UDP" option.

![graphite-teamcity](https://cloud.githubusercontent.com/assets/808557/6369313/5b84a826-bce5-11e4-8f59-ef89ba27ef55.PNG)

**Comment by sferencik** [comment]
pull request https://github.com/mendhak/teamcity-graphite/pull/3

**Comment by sferencik** [comment]
I've retested this now with the official zip, and it's working fine.
