### ISSUE TITLE
Metric key suffix

### ISSUE THREAD

**Issue by sferencik** [mendhak/teamcity-graphite#4]
Currently, the plugin allows specifying the metric key _prefix_. Can we add support for a _suffix_ too? I'd make a pull request.

I would find this useful to be able to create metric keys as follows:

```
stats.teamcity.native.artifactsize.BranchThree.vc11
      ^^^^^^^^^^^^^^^                               - the prefix representing the namespace (a concept)
                      ^^^^^^^^^^^^                  - the actual metric name/kind
                                   ^^^^^^^^^^^^^^^^ - the suffix specifies the branch and build configuration
```

**Comment by sferencik** [comment]
I forgot to say that to set up the suffix as "BranchTree.vc11" above, I would use TeamCity parameters. Thus, in the "Suffix" text box I would type something like `%teamcity.build.branch%.%system.teamcity.buildConfName%`. I find that quite appealing :-)

**Comment by mendhak** [comment]
Sure, suffix sounds like a good idea, happy to take a pull request!

**Comment by sferencik** [comment]
pull request: https://github.com/mendhak/teamcity-graphite/pull/5

**Comment by mendhak** [comment]
Thanks - merged in. Latest zip is in there.

**Comment by sferencik** [comment]
I've retested this now with the official zip, and it's working fine.
